export const MOCK = {
  CLIENTES: [
    { 
      id: "C-1042", 
      name: "Mercado El Sol S.A. de C.V.", 
      tipo: "B2B",
      rfc: "MES920101ABC",
      repName: "Lorena Pérez", 
      contactName: "Andrés García", 
      contactEmail: "lorena@elsol.mx", 
      contactPhone: "+52 55 4421 8810", 
      zone: "Zona Centro",
      fiscalCity: "CDMX", 
      fiscalState: "Ciudad de México",
      fiscalStreet: "Av. Reforma 123, Int 4",
      fiscalColonia: "Juárez",
      fiscalZip: "06600",
      fiscalRegime: "601 - General de Ley Personas Morales",
      cfdiUse: "G03 - Gastos en general",
      estado: "active",
      rating: "4.8",
      nombre: "Mercado El Sol S.A. de C.V.",
      contacto: "Andrés García"
    },
    { 
      id: "C-1043", 
      name: "Boutique Camelia S.A.", 
      tipo: "B2B",
      rfc: "BCA150315XYZ",
      repName: "Andrés Ruiz", 
      contactName: "Sofía Luna", 
      contactEmail: "hola@camelia.shop", 
      contactPhone: "+52 33 1209 4477", 
      zone: "Zona Occidente",
      fiscalCity: "Guadalajara", 
      fiscalState: "Jalisco",
      fiscalStreet: "Calzada Independencia 550",
      fiscalColonia: "Centro",
      fiscalZip: "44100",
      fiscalRegime: "601 - General de Ley Personas Morales",
      cfdiUse: "G03 - Gastos en general",
      estado: "active",
      rating: "5.0",
      nombre: "Boutique Camelia S.A.",
      contacto: "Sofía Luna"
    },
    { 
      id: "C-1044", 
      name: "TecnoStock México", 
      tipo: "B2B",
      rfc: "TSM201111999",
      repName: "Mariana López", 
      contactName: "Kevin Brown", 
      contactEmail: "ventas@tecnostock.mx", 
      contactPhone: "+52 81 2233 9001", 
      zone: "Zona Norte",
      fiscalCity: "Monterrey", 
      fiscalState: "Nuevo León",
      fiscalStreet: "Av. Constitución 1000",
      fiscalColonia: "Obispado",
      fiscalZip: "64060",
      fiscalRegime: "601 - General de Ley Personas Morales",
      cfdiUse: "I01 - Construcciones",
      estado: "inactive",
      rating: "3.5",
      nombre: "TecnoStock México",
      contacto: "Kevin Brown"
    },
    { 
      id: "C-1045", 
      name: "Distribuidora Colibrí", 
      tipo: "B2B",
      rfc: "DCO180604HJK",
      repName: "Patricia Méndez", 
      contactName: "Patricia M.", 
      contactEmail: "contacto@colibri.mx", 
      contactPhone: "+52 33 8800 1142", 
      zone: "Zona Occidente",
      fiscalCity: "Guadalajara", 
      fiscalState: "Jalisco",
      fiscalStreet: "Av. Vallarta 4500",
      fiscalColonia: "Zapopan",
      fiscalZip: "45040",
      fiscalRegime: "601 - General de Ley Personas Morales",
      cfdiUse: "G03 - Gastos en general",
      estado: "active",
      rating: "4.9",
      nombre: "Distribuidora Colibrí",
      contacto: "Patricia M."
    },
    { 
      id: "C-1046", 
      name: "Juan Pérez García", 
      tipo: "B2C",
      rfc: "PEGJ850101HDF",
      contactName: "Juan Pérez", 
      contactEmail: "juan.perez@gmail.com", 
      contactPhone: "+52 55 1122 3344", 
      zone: "Zona Centro",
      fiscalCity: "CDMX", 
      fiscalState: "Ciudad de México",
      fiscalStreet: "Calle Roble 45",
      fiscalColonia: "Polanco",
      fiscalZip: "11560",
      fiscalRegime: "605 - Sueldos y Salarios",
      cfdiUse: "S01 - Sin efectos fiscales",
      estado: "active",
      rating: "4.9",
      nombre: "Juan Pérez García",
      contacto: "Juan Pérez"
    },
    { 
      id: "C-1047", 
      name: "Mariana Rodríguez", 
      tipo: "B2C",
      rfc: "RODM900512LMN",
      contactName: "Mariana R.", 
      contactEmail: "mariana.rod@outlook.com", 
      contactPhone: "+52 33 9988 7766", 
      zone: "Zona Occidente",
      fiscalCity: "Zapopan", 
      fiscalState: "Jalisco",
      fiscalStreet: "Paseo de las Lomas 45",
      fiscalColonia: "Lomas de Zapopan",
      fiscalZip: "45130",
      fiscalRegime: "612 - Personas Físicas con Actividades Empresariales",
      cfdiUse: "G03 - Gastos en general",
      estado: "active",
      rating: "4.7",
      nombre: "Mariana Rodríguez",
      contacto: "Mariana R."
    },
    { 
      id: "C-1048", 
      name: "Carlos Vega", 
      tipo: "B2C",
      rfc: "VEGC770222TYU",
      contactName: "Carlos Vega", 
      contactEmail: "pedidos@laespiga.com", 
      contactPhone: "+52 222 414 0091", 
      zone: "Zona Sur",
      fiscalCity: "Puebla", 
      fiscalState: "Puebla",
      fiscalStreet: "Av. Juarez 33",
      fiscalColonia: "Centro",
      fiscalZip: "72000",
      fiscalRegime: "605 - Sueldos y Salarios",
      cfdiUse: "G03 - Gastos en general",
      estado: "active",
      rating: "4.6",
      nombre: "Carlos Vega",
      contacto: "Carlos Vega"
    }
  ],
  VEHICULOS: [
    { id: "V-101", placa: "C-123-AB", modelo: "Kenworth T680", año: "2023", peso: "25 Tons", volumen: "80 m³", combustible: "Diesel", tanque: "300 gal", rendimiento: "3.5 km/L", kilometraje: "45,200 km", estado: "disponible", driver: "Juan Pérez", tipo: "Tractocamión" },
    { id: "V-102", placa: "C-456-CD", modelo: "Freightliner Cascadia", año: "2022", peso: "20 Tons", volumen: "70 m³", combustible: "Diesel", tanque: "280 gal", rendimiento: "3.8 km/L", kilometraje: "88,100 km", estado: "en_viaje", driver: "Andrés García", tipo: "Remolque" },
    { id: "V-103", placa: "C-789-EF", modelo: "Isuzu Forward", año: "2024", peso: "8 Tons", volumen: "45 m³", combustible: "Diesel", tanque: "150 gal", rendimiento: "5.2 km/L", kilometraje: "12,400 km", estado: "disponible", driver: "Sin asignar", tipo: "Camión Rígido" },
    { id: "V-104", placa: "C-321-XY", modelo: "Volkswagen Delivery", año: "2021", peso: "3.5 Tons", volumen: "18 m³", combustible: "Gasolina", tanque: "80 L", rendimiento: "8.5 km/L", kilometraje: "112,000 km", estado: "mantenimiento", driver: "Kevin Brown", tipo: "Van de Carga" },
  ],
  PUNTOS_ENTREGA: [
    { 
      id: "PE-001", 
      nombre: "CEDIS Santa Fe", 
      direccion: "Av. Vasco de Quiroga 1200, Santa Fe, CDMX", 
      gps: "19.3629, -99.2687", 
      contacto: "Roberto Medina", 
      tel: "+52 55 1234 5678",
      client_id: "C-1042",
      status: "active",
      reception_days: [1,2,3,4,5],
      reception_from: "08:00",
      reception_to: "18:00",
      service_time_min: 60
    },
    { 
      id: "PE-002", 
      nombre: "Bodega Zapopan Industrial", 
      direccion: "Anillo Perif. Nte. 5100, Zapopan, Jal.", 
      gps: "20.7333, -103.4333", 
      contacto: "Lucía Fernández", 
      tel: "+52 33 9876 5432",
      client_id: "C-1043",
      status: "active",
      reception_days: [1,2,3,4,5,6],
      reception_from: "07:00",
      reception_to: "20:00",
      service_time_min: 45
    },
    { 
      id: "PE-003", 
      nombre: "Tienda Centro Monterrey", 
      direccion: "Av. Francisco I. Madero 300, Centro, Monterrey", 
      gps: "25.6866, -100.3161", 
      contacto: "Carlos Delgado", 
      tel: "+52 81 2233 4455",
      client_id: "C-1044",
      status: "inactive",
      reception_days: [1,2,3,4,5],
      reception_from: "10:00",
      reception_to: "19:00",
      service_time_min: 30
    }
  ],
  DRIVERS: [
    { id: "D-101", nombre: "Roberto Gómez", email: "roberto.gomez@cargalo.mx", tel: "55 1234 5678", ciudad: "CDMX", zona: "Centro", estado: "active", desde: "2023-01-15", rating: 4.8, envios: 124, gasto: 45000, entregas_hoy: 3, vehiculo: "Kenworth T680" },
    { id: "D-102", nombre: "Alejandro Ruiz", email: "a.ruiz@cargalo.mx", tel: "33 9876 5432", ciudad: "Guadalajara", zona: "Zapopan", estado: "active", desde: "2023-03-20", rating: 4.9, envios: 98, gasto: 32000, entregas_hoy: 2, vehiculo: "Freightliner Cascadia" },
    { id: "D-103", nombre: "Mariana López", email: "m.lopez@cargalo.mx", tel: "81 2233 4455", ciudad: "Monterrey", zona: "Santa Catarina", estado: "inactive", desde: "2022-11-05", rating: 4.5, envios: 210, gasto: 85000, entregas_hoy: 0, vehiculo: "Isuzu Forward" },
    { id: "D-104", nombre: "Carlos Ortiz", email: "c.ortiz@cargalo.mx", tel: "22 4140 0091", ciudad: "Puebla", zona: "Centro", estado: "suspended", desde: "2024-02-10", rating: 3.2, envios: 15, gasto: 5000, entregas_hoy: 0, vehiculo: "Volkswagen Delivery" }
  ]
};

export const VIAJES_MOCK = [
  { id: "V-1001", cliente: "Mercado El Sol S.A. de C.V.", driver: "Roberto Gómez", origen: "Av. Reforma 123, CDMX", destino: "Toluca, EdoMex", estado: "scheduled" },
  { id: "V-1002", cliente: "Boutique Camelia S.A.", driver: "Alejandro Ruiz", origen: "Guadalajara, Jal", destino: "Zapopan, Jal", estado: "in_transit" }
];
